---
title: Blocks Docs
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hunterae@gmail.com
description: How do you render your blocks of code?
baseurl: "/blocks"
url: ''
github_username: hunterae
markdown: kramdown
theme: jekyll-theme-slate
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
